steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/phrase-api-repo/phrase-api:latest', '.']
  
  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/phrase-api-repo/phrase-api:latest']
  
  # Initialize Terraform
  - name: 'hashicorp/terraform:1.5.0'
    args: ['init']
    dir: 'terraform'
  
  # Terraform Apply
  - name: 'hashicorp/terraform:1.5.0'
    args: ['apply', '-auto-approve', '-var=project_id=${_PROJECT_ID}', '-var=region=${_REGION}', '-var=gemini_api_key=${_GEMINI_API_KEY}']
    dir: 'terraform'

logsBucket: gs://cloudbuild-log-tough-flow-460911-j0
options:
  logging: GCS_ONLY

substitutions:
  _PROJECT_ID: your-project-id
  _REGION: us-central1
  _GEMINI_API_KEY: your-gemini-api-key